Scape zillow for neighborhood tables
========================================================

general method to clear workspacd

```{r}
#Setup by clearing all objects from work space
rm(list = ls(all = TRUE)) #CLEAR WORKSPACE
```
general way to scape out tables, if any

```{r}
library(XML)

theurl = seq(to=10)
theurl[1] = "http://www.zillow.com/homedetails/10106-NW-13th-Ave-Gainesville-FL-32606/42712542_zpid/"
theurl[2] = "http://www.zillow.com/homes/for_sale/house,townhouse_type/3-_beds/1-_baths/200000-400000_price/761-1521_mp/built_sort/29.678732,-82.441921,29.653263,-82.471747_rect/14_zm/3ecae538b6X1-CRzncwymrdu7jh_10veyp_crid/"
#theurl <- "http://en.wikipedia.org/wiki/Brazil_national_football_team"
tables <- readHTMLTable(theurl[1])
n.rows <- unlist(lapply(tables, function(t) dim(t)[1]))
d= as.data.frame(tables[1])
```
Another way
```{r}
library(RCurl)
library(XML)

# Download page using RCurl
# You may need to set proxy details, etc.,  in the call to getURL
#theurl <- "http://en.wikipedia.org/wiki/Brazil_national_football_team"
webpage <- getURL(theurl[1])
# Process escape characters
webpage <- readLines(tc <- textConnection(webpage)); close(tc)

# Parse the html tree, ignoring errors on the page
pagetree <- htmlTreeParse(webpage, error=function(...){})

# Navigate your way through the tree. It may be possible to do this more efficiently using getNodeSet
body <- pagetree$children$html$children$body 
divbodyContent <- body$children$div$children[[1]]$children$div$children[[4]]
tables <- divbodyContent$children[names(divbodyContent)=="table"]

#In this case, the required table is the only one with class "wikitable sortable"  
tableclasses <- sapply(tables, function(x) x$attributes["class"])
thetable  <- tables[which(tableclasses=="wikitable sortable")]$table

#Get columns headers
headers <- thetable$children[[1]]$children
columnnames <- unname(sapply(headers, function(x) x$children$text$value))

# Get rows from table

content <- c()
for(i in 2:length(thetable$children))
{
   tablerow <- thetable$children[[i]]$children
   opponent <- tablerow[[1]]$children[[2]]$children$text$value
   others <- unname(sapply(tablerow[-1], function(x) x$children$text$value)) 
   content <- rbind(content, c(opponent, others))
}

# Convert to data frame
colnames(content) <- columnnames
as.data.frame(content)```
```

You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
plot(d)
```

